---
title: "WaterLevel_24"
author: "Hannah Curtis"
date: "2024-05-20"
output: html_document
---
This file uses the raw pressure measurements from the pressure transducers to calculate water level at each pond during the 2024 field season. Additionally, water level and temperatures histograms are plotted in this file.

Updated: 5/20/24

Read pressure files:
```{r}

# Ponds
baxter <- read.csv("Baxter_Water_Level_all.csv")
baxter_depthm <- baxter$Depth.ft /3.28
commercialave <- read.csv("CommAve_Water_Level_all.csv")
commercialave_depthm <- commercialave$Depth.ft /3.28
commave_datetime <- as.POSIXct(commercialave$DateTime, format = "%m/%d/%Y %H:%M")
doba4 <- read.csv("DobA4_Water_Level_all_corrected.csv")
doba4_depthm <- doba4$Depth.ft /3.28
doba5 <- read.csv("DobA5_Water_Level_all.csv")
doba5_depthm <- doba5$Depth.ft /3.28
doba7 <- read.csv("DobA7_Water_Level_all.csv")
doba7_depthm <- doba7$Depth.ft /3.28
doba8 <- read.csv("DobA8_Water_Level_all.csv")
doba8_depthm <- doba8$Depth.ft /3.28
doba22 <- read.csv("DobA22_Water_Level_all.csv")
doba22_depthm <- doba22$Depth.ft /3.28
doorcreek <- read.csv("DoorCreek_Water_Level_all.csv")
doorcreek_depthm <- doorcreek$Depth.ft /3.28
elver <- read.csv("Elver_Water_Level_all.csv")
elver_depthm <- elver$Depth.ft /3.28
garner <- read.csv("Garner_Water_Level_all.csv")
garner_depthm <- garner$Depth.ft /3.28
greentree <- read.csv("Greentree_Water_Level_all.csv")
greentree_depthm <- greentree$Depth.ft /3.28
hospital <- read.csv("Hospital_Water_Level_all.csv")
hospital_depthm <- hospital$Depth.ft /3.28
hpchurch <- read.csv("HPChurch_Water_Level.csv")
hpchurch_depthm <- hpchurch$Depth.ft /3.28
lot60 <- read.csv("Lot60_Water_Level_all.csv")
lot60_depthm <- lot60$Depth.ft /3.28
madcity <- read.csv("MadCity_Water_Level_all.csv")
madcity_depthm <- madcity$Depth.ft /3.28
manitou <- read.csv("Manitou_Water_Level_all.csv")
manitou_depthm <- manitou$Depth.ft /3.28
mariondunn <- read.csv("MarionDunn_Water_Level_all.csv")
mariondunn_depthm <- mariondunn$Depth.ft /3.28
midtown <- read.csv("Midtown_Water_Level_all.csv")
midtown_depthm <- midtown$Depth.ft /3.28
owen <- read.csv("Owen_Water_Level_all.csv")
owen_depthm <- owen$Depth.ft /3.28
twofountains <- read.csv("TwoFountains_Water_Level_all.csv")
twofountains_depthm <- twofountains$Depth.ft /3.28

```

Water Level Plots
```{r}
# Water level plots
plot_pond <- function(pond_dates, depth, col, name) {
  plot(depth, type="l", col=col, lwd=3, pch=17, ylim = c(0,7),
     main=paste(name,"Water Level"), 
     xlab="Date", 
     ylab="Water Level (feet)", xaxt='n')
    # add a date axis
  grid()

  get_dates <- function(datetime) {
    d = strsplit(datetime,' ')[[1]][1]
    d = strsplit(d,'/')[[1]]
    return(paste(d[1], '/', d[2], sep=""))
  }
  
  dates = lapply(pond_dates,get_dates)
  idx_change=c()
  last_d = 0
  for (i in 1:length(dates)) {
    if (dates[[i]] != last_d) {
      idx_change = append(idx_change, i)
      last_d = dates[i]
    }
  }
    
  axis(1,at=idx_change,labels=dates[idx_change])
}
```

Pond Water Level Plots
```{r}
plot_pond(baxter$DateTime, baxter$Depth.ft, "dodgerblue4", "Baxter")
plot_pond(commercialave$DateTime, commercialave$Depth.ft, "#542E71", "Commercial Ave")
plot_pond(doba4$DateTime, doba4$Depth.ft, "green", "Dobson A4")
plot_pond(doba5$DateTime, doba5$Depth.ft, "gold", "Dobson A5")
plot_pond(doba7$DateTime, doba7$Depth.ft, "magenta", "Dobson A7")
plot_pond(doba8$DateTime, doba8$Depth.ft, "orange", "Dobson A8")
plot_pond(doba22$DateTime, doba22$Depth.ft, "gray", "Dobson A22")
plot_pond(doorcreek$DateTime, doorcreek$Depth.ft, "purple", "Door Creek")
plot_pond(elver$DateTime, elver$Depth.ft, "brown", "Elver")
plot_pond(garner$DateTime, garner$Depth.ft, "skyblue", "Garner")
plot_pond(greentree$DateTime, greentree$Depth.ft, "coral1", "Greentree")
plot_pond(hospital$DateTime, hospital$Depth.ft, "lavender", "Hospital")
plot_pond(hpchurch$DateTime, hpchurch$Depth.ft, "forestgreen", "High Point Church")
plot_pond(lot60$DateTime, lot60$Depth.ft, "yellow", "Lot 60")
plot_pond(madcity$DateTime, madcity$Depth.ft, "maroon", "Mad City")
plot_pond(manitou$DateTime, manitou$Depth.ft, "pink", "Manitou")
plot_pond(mariondunn$DateTime, mariondunn$Depth.ft, "royalblue", "Marion-Dunn")
plot_pond(midtown$DateTime, midtown$Depth.ft, "lightsalmon", "Midtown")
plot_pond(owen$DateTime, owen$Depth.ft, "tan", "Owen")
plot_pond(twofountains$DateTime, twofountains$Depth.ft, "darkgray", "Two Fountains")

```
```{r}
plot_histd <- function(pond_depth, color, name) {
  hist(pond_depth, probability=TRUE, breaks=100, xlim=c(0,2), main=paste(name), xlab="Water Level (ft)", ylab="Density", col=color, border=color)
  lines(density(pond_depth), col="black", lwd=2)
  grid()
  box()
}
```

```{r}
bax_hist <- plot_histd(baxter_depthm, "dodgerblue4", "Baxter")
commave_hist <- plot_histd(commercialave_depthm, "#542E71", "Commercial Ave")
doba4_hist <- plot_histd(doba4_depthm, "green", "Dobson A4")
doba5_hist <- plot_histd(doba5_depthm, "gold", "Dobson A5")
doba7_hist <- plot_histd(doba7_depthm, "magenta", "Dobson A7")
doba8_hist <- plot_histd(doba8_depthm, "orange", "Dobson A8")
doba22_hist <- plot_histd(doba22_depthm, "gray", "Dobson A22")
doorcreek_hist <- plot_histd(doorcreek_depthm, "purple", "Door Creek")
elver_hist <- plot_histd(elver_depthm, "brown", "Elver")
garner_hist <- plot_histd(garner_depthm, "skyblue", "Garner")
greentree_hist <- plot_histd(greentree_depthm, "coral1", "Greentree")
hpchurch_hist <- plot_histd(na.omit(hpchurch_depthm), "forestgreen", "High Point Church")
hospital_hist <- plot_histd(hospital_depthm, "lavender", "Hospital")
lot60_hist <- plot_histd(lot60_depthm, "yellow", "Lot 60")
madcity_hist <- plot_histd(madcity_depthm, "maroon", "Mad City")
manitou_hist <- plot_histd(manitou_depthm, "pink", "Manitou")
mariondunn_hist <- plot_histd(mariondunn_depthm, "royalblue", "Marion-Dunn")
midtown_hist <- plot_histd(midtown_depthm, "lightsalmon", "Midtown")
owen_hist <- plot_histd(owen_depthm, "tan", "Owen")
twofountains_hist <- plot_histd(twofountains_depthm, "darkgray", "Two Fountains")
```

```{r}
plot(commave_datetime[27150:28450], commercialave_depthm[27150:28450], type="l", lwd=2, xlab="Date", ylab = "Water Level (m)", col="#84A9C0")


```
```{r}
plot_histd <- function(pond_depth, color) {
  hist(pond_depth, probability=TRUE, breaks=100, xlim=c(0,1.7), main="",xlab="Water Level (m)", ylab="Density", col=color, border=color)
  lines(density(pond_depth), col="black", lwd=2)
  abline(v=1.9/3.28,lwd=2, col="black")
  box()
  # Add legend
legend("topright",               # Position in the top-right corner
       legend = "Outlet Location", # Label for the legend
       lty = 1, lwd=2,                    # Line type (solid line)
       col = "black",              # Color of the line
       bty = "y")                  # No box around the legend
}

commave_histd <- plot_histd(commercialave_depthm, "#84A9C0")
```
Boxplots
```{r}
storm_data <- read.csv("Boxplots_Storm.csv")
bounce_m <- storm_data$Max.Bounce / 3.28
regime_data <- read.csv("Boxplots_Regime.csv")

# Bounce
png("bounce_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(bounce_m, ylab="Bounce (m)", col = "#082D0F", cex.axis=2, cex.lab=2)
points(1, 2.213/3.28, col = "#84A9C0", pch = 8)
dev.off()

# Rate of WL Increase
png("increaserate_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(storm_data$Inflow.Rate, ylab="Rate of Water Level Increase", col = "#6A66A3", cex.axis=2, cex.lab=2)
points(1, 8.7, col = "#84A9C0", pch = 8)
dev.off()

# Gradual Decline Rate
png("declinerate_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(storm_data$Decline.Rate, ylab="Rate of Gradual Decline", col = "#542E71", cex.axis=2, cex.lab=2)
points(1, -0.051147418, col = "#84A9C0", pch = 8)
dev.off()

# Skewness of WL Histogram
png("skewness_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(regime_data$Pond.Skewness, ylab="Skewness of Histogram", col = "#B3CBB9", cex.axis=2, cex.lab=2)
points(1, 0.680338784, col = "#84A9C0", pch = 8)
dev.off()

# Variance of WL Histogram
png("variance_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(regime_data$Pond.Variance, ylab="Variance of Histogram", col = "#38405F", cex.axis=2, cex.lab=2)
points(1, 0.212469242, col = "#84A9C0", pch = 8)
dev.off()

# % Days WL near Mode
png("mode_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(regime_data$Contant.Water.Level.6in, ylab="% of Days Water Level Near Mode", col = "#6A66A3", cex.axis=2, cex.lab=2)
points(1, 49.39186084, col = "#84A9C0", pch = 8)
dev.off()

# % Days WL near Outlet
png("outlet_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(regime_data$Outlet.Water.Level, ylab="% of Days Water Level Near Outlet", col = "#082D0F", cex.axis=2, cex.lab=2)
points(1, 48.08807411, col = "#84A9C0", pch = 8)
dev.off()

# % Days WL Below Outlet
png("belowoutlet_boxplot.png", width = 400, height = 800)  # Width and height in pixels
par(mar = c(5, 5, 4, 2))  # Increase left margin space
boxplot(regime_data$Below.Outlet.Water.Level, ylab="% of Days Water Level Below Outlet", col = "#542E71", cex.axis=2, cex.lab=2)
points(1, 45.83318601, col = "#84A9C0", pch = 8)
dev.off()
```

